######################################################################
## PARAM_CARD AUTOMATICALY GENERATED BY MG5 FOLLOWING UFO MODEL   ####
######################################################################
##                                                                  ##
##  Width set on Auto will be computed following the information    ##
##        present in the decay.py files of the model.               ##
##        See  arXiv:1402.1178 for more details.                    ##
##                                                                  ##
######################################################################

###################################
## INFORMATION FOR MASS
###################################
Block mass 
    5 4.180000e+00 # MB 
    6 1.727600e+02 # MT 
   23 9.118760e+01 # MZ 
   25 1.250900e+02 # MH 
## Dependent parameters, given by model restrictions.
## Those values should be edited following the 
## analytical expression. MG5 ignores those values 
## but they are important for interfacing the output of MG5
## to external program such as Pythia.
  1 0.000000e+00 # d : 0.0 
  2 0.000000e+00 # u : 0.0 
  3 0.000000e+00 # s : 0.0 
  4 0.000000e+00 # c : 0.0 
  11 0.000000e+00 # e- : 0.0 
  12 0.000000e+00 # ve : 0.0 
  13 0.000000e+00 # mu- : 0.0 
  14 0.000000e+00 # vm : 0.0 
  15 0.000000e+00 # ta- : 0.0 
  16 0.000000e+00 # vt : 0.0 
  21 0.000000e+00 # g : 0.0 
  22 0.000000e+00 # a : 0.0 
  9000005 9.118760e+01 # z1 : MZ 
  9000006 8.038700e+01 # w1+ : MWsm 
  9000007 1.727600e+02 # t1 : MT 
  9000008 1.250900e+02 # h1 : MH 
  24 8.038700e+01 # w+ : MW 

###################################
## INFORMATION FOR SMEFT
###################################
Block smeft 
    1 0.000000e+00 # cG 
    2 0.000000e+00 # cW 
    3 0.000000e+00 # cH 
    4 0.000000e+00 # cHbox 
    5 0.000000e+00 # cHDD 
    6 0.000000e+00 # cHG 
    7 0.000000e+00 # cHW 
    8 0.000000e+00 # cHB 
    9 0.000000e+00 # cHWB 
   10 0.000000e+00 # ceHRe11 
   11 0.000000e+00 # ceHRe22 
   12 0.000000e+00 # ceHRe33 
   19 0.000000e+00 # cuHRe11 
   20 0.000000e+00 # cuHRe22 
   21 0.000000e+00 # cuHRe33 
   28 0.000000e+00 # cdHRe11 
   29 0.000000e+00 # cdHRe22 
   30 0.000000e+00 # cdHRe33 
   37 0.000000e+00 # ceWRe11 
   38 0.000000e+00 # ceWRe22 
   39 0.000000e+00 # ceWRe33 
   46 0.000000e+00 # ceBRe11 
   47 0.000000e+00 # ceBRe22 
   48 0.000000e+00 # ceBRe33 
   55 0.000000e+00 # cuGRe11 
   56 0.000000e+00 # cuGRe22 
   57 0.000000e+00 # cuGRe33 
   64 0.000000e+00 # cuWRe11 
   65 0.000000e+00 # cuWRe22 
   66 0.000000e+00 # cuWRe33 
   73 0.000000e+00 # cuBRe11 
   74 0.000000e+00 # cuBRe22 
   75 0.000000e+00 # cuBRe33 
   82 0.000000e+00 # cdGRe11 
   83 0.000000e+00 # cdGRe22 
   84 0.000000e+00 # cdGRe33 
   91 0.000000e+00 # cdWRe11 
   92 0.000000e+00 # cdWRe22 
   93 0.000000e+00 # cdWRe33 
  100 0.000000e+00 # cdBRe11 
  101 0.000000e+00 # cdBRe22 
  102 0.000000e+00 # cdBRe33 
  109 0.000000e+00 # cHl1Re11 
  112 0.000000e+00 # cHl1Re22 
  114 0.000000e+00 # cHl1Re33 
  115 0.000000e+00 # cHl3Re11 
  118 0.000000e+00 # cHl3Re22 
  120 0.000000e+00 # cHl3Re33 
  121 0.000000e+00 # cHq1Re11 
  124 0.000000e+00 # cHq1Re22 
  126 0.000000e+00 # cHq1Re33 
  127 0.000000e+00 # cHq3Re11 
  130 0.000000e+00 # cHq3Re22 
  132 0.000000e+00 # cHq3Re33 
  133 0.000000e+00 # cHeRe11 
  136 0.000000e+00 # cHeRe22 
  138 0.000000e+00 # cHeRe33 
  139 0.000000e+00 # cHuRe11 
  142 0.000000e+00 # cHuRe22 
  144 0.000000e+00 # cHuRe33 
  145 0.000000e+00 # cHdRe11 
  148 0.000000e+00 # cHdRe22 
  150 0.000000e+00 # cHdRe33 
  151 0.000000e+00 # cHudRe11 
  152 0.000000e+00 # cHudRe22 
  153 0.000000e+00 # cHudRe33 
  160 0.000000e+00 # cllRe1111 
  161 0.000000e+00 # cllRe1122 
  162 0.000000e+00 # cllRe1221 
  163 0.000000e+00 # cllRe1133 
  164 0.000000e+00 # cllRe1331 
  165 0.000000e+00 # cllRe2222 
  166 0.000000e+00 # cllRe2233 
  167 0.000000e+00 # cllRe2332 
  168 0.000000e+00 # cllRe3333 
  172 0.000000e+00 # cllRe1212 
  179 0.000000e+00 # cllRe1313 
  185 0.000000e+00 # cllRe2323 
  187 0.000000e+00 # cqq1Re1111 
  188 0.000000e+00 # cqq1Re1122 
  189 0.000000e+00 # cqq1Re1221 
  190 0.000000e+00 # cqq1Re1133 
  191 0.000000e+00 # cqq1Re1331 
  192 0.000000e+00 # cqq1Re2222 
  193 0.000000e+00 # cqq1Re2233 
  194 0.000000e+00 # cqq1Re2332 
  195 0.000000e+00 # cqq1Re3333 
  199 0.000000e+00 # cqq1Re1212 
  206 0.000000e+00 # cqq1Re1313 
  212 0.000000e+00 # cqq1Re2323 
  214 0.000000e+00 # cqq3Re1111 
  215 0.000000e+00 # cqq3Re1122 
  216 0.000000e+00 # cqq3Re1221 
  217 0.000000e+00 # cqq3Re1133 
  218 0.000000e+00 # cqq3Re1331 
  219 0.000000e+00 # cqq3Re2222 
  220 0.000000e+00 # cqq3Re2233 
  221 0.000000e+00 # cqq3Re2332 
  222 0.000000e+00 # cqq3Re3333 
  226 0.000000e+00 # cqq3Re1212 
  233 0.000000e+00 # cqq3Re1313 
  239 0.000000e+00 # cqq3Re2323 
  241 0.000000e+00 # clq1Re1111 
  245 0.000000e+00 # clq1Re1122 
  246 0.000000e+00 # clq1Re1133 
  265 0.000000e+00 # clq1Re2211 
  268 0.000000e+00 # clq1Re2222 
  270 0.000000e+00 # clq1Re2233 
  280 0.000000e+00 # clq1Re3311 
  283 0.000000e+00 # clq1Re3322 
  284 0.000000e+00 # clq1Re3333 
  286 0.000000e+00 # clq3Re1111 
  290 0.000000e+00 # clq3Re1122 
  291 0.000000e+00 # clq3Re1133 
  310 0.000000e+00 # clq3Re2211 
  313 0.000000e+00 # clq3Re2222 
  315 0.000000e+00 # clq3Re2233 
  325 0.000000e+00 # clq3Re3311 
  328 0.000000e+00 # clq3Re3322 
  329 0.000000e+00 # clq3Re3333 
  331 0.000000e+00 # ceeRe1111 
  332 0.000000e+00 # ceeRe1122 
  333 0.000000e+00 # ceeRe1133 
  334 0.000000e+00 # ceeRe2222 
  335 0.000000e+00 # ceeRe2233 
  336 0.000000e+00 # ceeRe3333 
  341 0.000000e+00 # ceeRe1212 
  344 0.000000e+00 # ceeRe1313 
  351 0.000000e+00 # ceeRe2323 
  352 0.000000e+00 # cuuRe1111 
  353 0.000000e+00 # cuuRe1122 
  354 0.000000e+00 # cuuRe1221 
  355 0.000000e+00 # cuuRe1133 
  356 0.000000e+00 # cuuRe1331 
  357 0.000000e+00 # cuuRe2222 
  358 0.000000e+00 # cuuRe2233 
  359 0.000000e+00 # cuuRe2332 
  360 0.000000e+00 # cuuRe3333 
  364 0.000000e+00 # cuuRe1212 
  371 0.000000e+00 # cuuRe1313 
  377 0.000000e+00 # cuuRe2323 
  379 0.000000e+00 # cddRe1111 
  380 0.000000e+00 # cddRe1122 
  381 0.000000e+00 # cddRe1221 
  382 0.000000e+00 # cddRe1133 
  383 0.000000e+00 # cddRe1331 
  384 0.000000e+00 # cddRe2222 
  385 0.000000e+00 # cddRe2233 
  386 0.000000e+00 # cddRe2332 
  387 0.000000e+00 # cddRe3333 
  391 0.000000e+00 # cddRe1212 
  398 0.000000e+00 # cddRe1313 
  404 0.000000e+00 # cddRe2323 
  406 0.000000e+00 # ceuRe1111 
  410 0.000000e+00 # ceuRe1122 
  411 0.000000e+00 # ceuRe1133 
  430 0.000000e+00 # ceuRe2211 
  433 0.000000e+00 # ceuRe2222 
  434 0.000000e+00 # ceuRe2223 
  435 0.000000e+00 # ceuRe2233 
  445 0.000000e+00 # ceuRe3311 
  448 0.000000e+00 # ceuRe3322 
  449 0.000000e+00 # ceuRe3333 
  451 0.000000e+00 # cedRe1111 
  455 0.000000e+00 # cedRe1122 
  456 0.000000e+00 # cedRe1133 
  475 0.000000e+00 # cedRe2211 
  478 0.000000e+00 # cedRe2222 
  480 0.000000e+00 # cedRe2233 
  490 0.000000e+00 # cedRe3311 
  493 0.000000e+00 # cedRe3322 
  494 0.000000e+00 # cedRe3333 
  496 0.000000e+00 # cud1Re1111 
  500 0.000000e+00 # cud1Re1122 
  501 0.000000e+00 # cud1Re1133 
  520 0.000000e+00 # cud1Re2211 
  523 0.000000e+00 # cud1Re2222 
  525 0.000000e+00 # cud1Re2233 
  535 0.000000e+00 # cud1Re3311 
  538 0.000000e+00 # cud1Re3322 
  539 0.000000e+00 # cud1Re3333 
  541 0.000000e+00 # cud8Re1111 
  545 0.000000e+00 # cud8Re1122 
  546 0.000000e+00 # cud8Re1133 
  565 0.000000e+00 # cud8Re2211 
  568 0.000000e+00 # cud8Re2222 
  569 0.000000e+00 # cud8Re2223 
  570 0.000000e+00 # cud8Re2233 
  580 0.000000e+00 # cud8Re3311 
  583 0.000000e+00 # cud8Re3322 
  584 0.000000e+00 # cud8Re3333 
  586 0.000000e+00 # cleRe1111 
  590 0.000000e+00 # cleRe1122 
  591 0.000000e+00 # cleRe1133 
  610 0.000000e+00 # cleRe2211 
  613 0.000000e+00 # cleRe2222 
  615 0.000000e+00 # cleRe2233 
  625 0.000000e+00 # cleRe3311 
  628 0.000000e+00 # cleRe3322 
  629 0.000000e+00 # cleRe3333 
  631 0.000000e+00 # cluRe1111 
  635 0.000000e+00 # cluRe1122 
  636 0.000000e+00 # cluRe1133 
  655 0.000000e+00 # cluRe2211 
  658 0.000000e+00 # cluRe2222 
  660 0.000000e+00 # cluRe2233 
  670 0.000000e+00 # cluRe3311 
  673 0.000000e+00 # cluRe3322 
  674 0.000000e+00 # cluRe3333 
  676 0.000000e+00 # cldRe1111 
  680 0.000000e+00 # cldRe1122 
  681 0.000000e+00 # cldRe1133 
  700 0.000000e+00 # cldRe2211 
  703 0.000000e+00 # cldRe2222 
  705 0.000000e+00 # cldRe2233 
  715 0.000000e+00 # cldRe3311 
  718 0.000000e+00 # cldRe3322 
  719 0.000000e+00 # cldRe3333 
  721 0.000000e+00 # cqeRe1111 
  725 0.000000e+00 # cqeRe1122 
  726 0.000000e+00 # cqeRe1133 
  745 0.000000e+00 # cqeRe2211 
  748 0.000000e+00 # cqeRe2222 
  750 0.000000e+00 # cqeRe2233 
  760 0.000000e+00 # cqeRe3311 
  763 0.000000e+00 # cqeRe3322 
  764 0.000000e+00 # cqeRe3333 
  766 0.000000e+00 # cqu1Re1111 
  770 0.000000e+00 # cqu1Re1122 
  771 0.000000e+00 # cqu1Re1133 
  790 0.000000e+00 # cqu1Re2211 
  793 0.000000e+00 # cqu1Re2222 
  795 0.000000e+00 # cqu1Re2233 
  805 0.000000e+00 # cqu1Re3311 
  808 0.000000e+00 # cqu1Re3322 
  809 0.000000e+00 # cqu1Re3333 
  811 0.000000e+00 # cqu8Re1111 
  815 0.000000e+00 # cqu8Re1122 
  816 0.000000e+00 # cqu8Re1133 
  835 0.000000e+00 # cqu8Re2211 
  838 0.000000e+00 # cqu8Re2222 
  840 0.000000e+00 # cqu8Re2233 
  850 0.000000e+00 # cqu8Re3311 
  853 0.000000e+00 # cqu8Re3322 
  854 0.000000e+00 # cqu8Re3333 
  856 0.000000e+00 # cqd1Re1111 
  860 0.000000e+00 # cqd1Re1122 
  861 0.000000e+00 # cqd1Re1133 
  880 0.000000e+00 # cqd1Re2211 
  883 0.000000e+00 # cqd1Re2222 
  885 0.000000e+00 # cqd1Re2233 
  895 0.000000e+00 # cqd1Re3311 
  898 0.000000e+00 # cqd1Re3322 
  899 0.000000e+00 # cqd1Re3333 
  901 0.000000e+00 # cqd8Re1111 
  905 0.000000e+00 # cqd8Re1122 
  906 0.000000e+00 # cqd8Re1133 
  925 0.000000e+00 # cqd8Re2211 
  928 0.000000e+00 # cqd8Re2222 
  930 0.000000e+00 # cqd8Re2233 
  940 0.000000e+00 # cqd8Re3311 
  943 0.000000e+00 # cqd8Re3322 
  944 0.000000e+00 # cqd8Re3333 
  946 0.000000e+00 # cledqRe1111 
  950 0.000000e+00 # cledqRe1122 
  954 0.000000e+00 # cledqRe1133 
  955 0.000000e+00 # cledqRe2211 
  959 0.000000e+00 # cledqRe2222 
  963 0.000000e+00 # cledqRe2233 
  964 0.000000e+00 # cledqRe3311 
  968 0.000000e+00 # cledqRe3322 
  972 0.000000e+00 # cledqRe3333 
  1027 0.000000e+00 # cquqd1Re1111 
  1031 0.000000e+00 # cquqd1Re1122 
  1035 0.000000e+00 # cquqd1Re1133 
  1036 0.000000e+00 # cquqd1Re2211 
  1040 0.000000e+00 # cquqd1Re2222 
  1044 0.000000e+00 # cquqd1Re2233 
  1045 0.000000e+00 # cquqd1Re3311 
  1049 0.000000e+00 # cquqd1Re3322 
  1053 0.000000e+00 # cquqd1Re3333 
  1108 0.000000e+00 # cquqd8Re1111 
  1112 0.000000e+00 # cquqd8Re1122 
  1116 0.000000e+00 # cquqd8Re1133 
  1117 0.000000e+00 # cquqd8Re2211 
  1121 0.000000e+00 # cquqd8Re2222 
  1125 0.000000e+00 # cquqd8Re2233 
  1126 0.000000e+00 # cquqd8Re3311 
  1130 0.000000e+00 # cquqd8Re3322 
  1134 0.000000e+00 # cquqd8Re3333 
  1189 0.000000e+00 # clequ1Re1111 
  1193 0.000000e+00 # clequ1Re1122 
  1197 0.000000e+00 # clequ1Re1133 
  1198 0.000000e+00 # clequ1Re2211 
  1202 0.000000e+00 # clequ1Re2222 
  1206 0.000000e+00 # clequ1Re2233 
  1207 0.000000e+00 # clequ1Re3311 
  1211 0.000000e+00 # clequ1Re3322 
  1215 0.000000e+00 # clequ1Re3333 
  1270 0.000000e+00 # clequ3Re1111 
  1274 0.000000e+00 # clequ3Re1122 
  1278 0.000000e+00 # clequ3Re1133 
  1279 0.000000e+00 # clequ3Re2211 
  1283 0.000000e+00 # clequ3Re2222 
  1287 0.000000e+00 # clequ3Re2233 
  1288 0.000000e+00 # clequ3Re3311 
  1292 0.000000e+00 # clequ3Re3322 
  1296 0.000000e+00 # clequ3Re3333 

###################################
## INFORMATION FOR SMEFTCUTOFF
###################################
Block smeftcutoff 
    1 1.000000e+03 # LambdaSMEFT 

###################################
## INFORMATION FOR SMINPUTS
###################################
Block sminputs 
    1 8.038700e+01 # MW 
    2 1.166379e-05 # Gf 
    3 1.179000e-01 # aS 

###################################
## INFORMATION FOR YUKAWA
###################################
Block yukawa 
    5 4.180000e+00 # ymb 
    6 1.727600e+02 # ymt 

###################################
## INFORMATION FOR DECAY
###################################
DECAY   6 1.330000e+00 # WT 
DECAY  23 2.495200e+00 # WZ 
DECAY  24 2.085000e+00 # WW 
DECAY  25 4.070000e-03 # WH 
## Dependent parameters, given by model restrictions.
## Those values should be edited following the 
## analytical expression. MG5 ignores those values 
## but they are important for interfacing the output of MG5
## to external program such as Pythia.
DECAY  1 0.000000e+00 # d : 0.0 
DECAY  2 0.000000e+00 # u : 0.0 
DECAY  3 0.000000e+00 # s : 0.0 
DECAY  4 0.000000e+00 # c : 0.0 
DECAY  5 0.000000e+00 # b : 0.0 
DECAY  11 0.000000e+00 # e- : 0.0 
DECAY  12 0.000000e+00 # ve : 0.0 
DECAY  13 0.000000e+00 # mu- : 0.0 
DECAY  14 0.000000e+00 # vm : 0.0 
DECAY  15 0.000000e+00 # ta- : 0.0 
DECAY  16 0.000000e+00 # vt : 0.0 
DECAY  21 0.000000e+00 # g : 0.0 
DECAY  22 0.000000e+00 # a : 0.0 
DECAY  9000005 2.495200e+00 # z1 : WZ 
DECAY  9000006 2.085000e+00 # w1+ : WW 
DECAY  9000007 1.330000e+00 # t1 : WT 
DECAY  9000008 4.070000e-03 # h1 : WH 
#===========================================================
# QUANTUM NUMBERS OF NEW STATE(S) (NON SM PDG CODE)
#===========================================================

Block QNUMBERS 9000005  # z1 
        1 0  # 3 times electric charge
        2 3  # number of spin states (2S+1)
        3 1  # colour rep (1: singlet, 3: triplet, 8: octet)
        4 0  # Particle/Antiparticle distinction (0=own anti)
Block QNUMBERS 9000006  # w1+ 
        1 3  # 3 times electric charge
        2 3  # number of spin states (2S+1)
        3 1  # colour rep (1: singlet, 3: triplet, 8: octet)
        4 1  # Particle/Antiparticle distinction (0=own anti)
Block QNUMBERS 9000007  # t1 
        1 2  # 3 times electric charge
        2 2  # number of spin states (2S+1)
        3 3  # colour rep (1: singlet, 3: triplet, 8: octet)
        4 1  # Particle/Antiparticle distinction (0=own anti)
Block QNUMBERS 9000008  # h1 
        1 0  # 3 times electric charge
        2 1  # number of spin states (2S+1)
        3 1  # colour rep (1: singlet, 3: triplet, 8: octet)
        4 0  # Particle/Antiparticle distinction (0=own anti)
