ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION MDL_MH1,MDL_MT,MDL_MW,MDL_MZ,MDL_MZ1,MDL_MB
     $ ,MDL_MW1,MDL_MH,MDL_MT1

      COMMON/MASSES/ MDL_MH1,MDL_MT,MDL_MW,MDL_MZ,MDL_MZ1,MDL_MB
     $ ,MDL_MW1,MDL_MH,MDL_MT1


      DOUBLE PRECISION MDL_WH1,MDL_WH,MDL_WW,MDL_WT,MDL_WZ,MDL_WW1
     $ ,MDL_WT1,MDL_WZ1

      COMMON/WIDTHS/ MDL_WH1,MDL_WH,MDL_WW,MDL_WT,MDL_WZ,MDL_WW1
     $ ,MDL_WT1,MDL_WZ1


      DOUBLE COMPLEX GC_1, GC_2, GC_3, GC_5923, GC_6212, GC_6213,
     $  GC_6214

      COMMON/COUPLINGS/ GC_1, GC_2, GC_3, GC_5923, GC_6212, GC_6213,
     $  GC_6214

